#!/bin/bash
#
# douane      This shell script takes care of starting and stopping
#             douane daemon (A modern applicatif firewall)
#
# Author: Guillaume Hain zedtux@zedroot.org
#
# description: douane is the daemon process of the Douane firewall application. \
# This firewall is limiting access to the internet on application bases.

# Source function library.
. /lib/lsb/init-functions

NAME=douaned
DOUANEDIR=/opt/douane
DAEMON=$DOUANEDIR/$NAME
PIDDIR=$DOUANEDIR/pids
PIDFILE=$PIDDIR/$NAME.pid
STARTPIDFILE=$DOUANEDIR/logs/startpid

case "$1" in
    start)
        log_daemon_msg "Starting the $NAME daemon"
        if [ ! -e $PIDDIR ]; then
            mkdir $PIDDIR
            chown root $PIDDIR
        fi
        FULL_COMMAND="start-stop-daemon --start --oknodo --startas $DAEMON --make-pidfile --background --umask 0 --nicelevel -20 --pidfile $PIDFILE -- --debug"
        if [ x"$DAEMON_USER" != x ]; then
            sudo -u $DAEMON_USER $FULL_COMMAND
        else
            $FULL_COMMAND
        fi
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $NAME daemon"
        start-stop-daemon --retry 30 --stop --pidfile $PIDFILE
        if [ -a $PIDFILE ]; then rm $PIDFILE; fi;
        log_end_msg $?
        ;;
    status)
        status_of_proc $DAEMON $NAME
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage:  {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?
